import json
import yt_dlp
import os
from datetime import datetime, timedelta, timezone

# Configuration
INPUT_FILE = 'ytube.json'
OUTPUT_FILE = 'playlist.m3u'

def get_ist_time():
    """
    Returns the current time formatted in IST (UTC+05:30).
    GitHub servers use UTC, so we must add the offset manually.
    """
    # Get current UTC time
    utc_now = datetime.now(timezone.utc)
    # Create IST offset (5 hours, 30 minutes)
    ist_offset = timedelta(hours=5, minutes=30)
    # Calculate IST time
    ist_now = utc_now + ist_offset
    return ist_now.strftime('%Y-%m-%d %H:%M:%S IST')

def get_live_url(youtube_url):
    ydl_opts = {
        'quiet': True,
        'no_warnings': True,
        'format': 'all', 
        'live_from_start': True,
        'geo_bypass': True,
    }

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(youtube_url, download=False)
            
            # Find all formats that are m3u8
            m3u8_formats = [f for f in info.get('formats', []) if 'm3u8' in f.get('protocol', '') or '.m3u8' in f.get('url', '')]
            
            if not m3u8_formats:
                return None

            # Sort by bitrate (highest quality first)
            best_format = sorted(m3u8_formats, key=lambda x: x.get('tbr', 0) or 0, reverse=True)[0]
            return best_format['url']
                
    except Exception:
        return None

def generate_playlist():
    if not os.path.exists(INPUT_FILE):
        print(f"Error: {INPUT_FILE} not found.")
        return

    try:
        with open(INPUT_FILE, 'r', encoding='utf-8') as f:
            channels = json.load(f)
    except Exception:
        print("Error: JSON file is invalid.")
        return

    # 1. Add Header and Time Stamp
    current_time = get_ist_time()
    m3u_content = ["#EXTM3U"]
    m3u_content.append(f"# Playlist Updated: {current_time}")
    m3u_content.append(f"# Generated by Automated Script")
    
    print(f"Starting Update: {current_time}")
    print(f"Processing {len(channels)} channels...")

    count = 0
    for channel in channels:
        name = channel.get('name', 'Unknown')
        url = channel.get('url')
        group = channel.get('group', 'General')
        logo = channel.get('logo', '')

        print(f"Fetching: {name}...", end=" ", flush=True)
        
        stream_url = get_live_url(url)

        if stream_url:
            # Add channel to playlist
            m3u_content.append(f'#EXTINF:-1 group-title="{group}" tvg-logo="{logo}",{name}')
            m3u_content.append(stream_url)
            print("OK")
            count += 1
        else:
            print("FAILED (Offline/Blocked)")

    # Write to file
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write("\n".join(m3u_content))
    
    print(f"\nDone. Updated {OUTPUT_FILE} at {current_time}")

if __name__ == "__main__":
    generate_playlist()
